# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeRealCloneCoding' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeRealCloneCoding
  pod 'SnapKit', '~> 5.6.0'
  target 'BeRealCloneCodingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeRealCloneCodingUITests' do
    # Pods for testing
  end

end
